//Understand why freezed used with bloc

import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
part 'person.freezed.dart';//The generated code from freezed will be in person.freezed.dart

@freezed // It is the  annotation from freezed_annotation used to show this class is generated by freezed
abstract class Person with _$Person //(generated file )freezed package is  generated in the file named _$Person || base class that freezed uses to generate code

// with : connect our abstract class to _$Person (the generated file)
{
  // to create |Person class|
  const factory Person({
    required String name,
    required int age,
  }) = _Person; //generated class by freezed for this.
}











   /*  
   tostring() method || mainly used for : convert the object into a human-readable string.

   ^^^^^^^^^^^^^^
   WITHOUT TO STRING METHOD 
   ----------------------------------


   class User {
  String name;
  int age;

  User(this.name, this.age);

  @override
  String toString() {
    return 'User(name: $name, age: $age)';
  }
}

void main() {
  var user = User('John', 25);
  print(user); // output: User(name: John, age: 25)
}

    */